# Generated by Django 2.1.8 on 2020-01-05 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_ID', models.TextField(max_length=15)),
                ('phase', models.TextField(max_length=1)),
                ('total_days', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourtDates',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('court_date_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('court_date', models.DateField(db_column='court_date')),
                ('event', models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Phase Appearance', 'Phase Appearance'), ('Graduation', 'Graduation'), ('Termination', 'Termination'), ('Special', 'Special')], max_length=50, null=True)),
                ('court_date_type', models.CharField(blank=True, choices=[('New', 'New'), ('Review', 'Review'), ('Final', 'Final')], db_column='CourtDateType', max_length=10, null=True)),
                ('phase', models.TextField(max_length=1)),
                ('attendance', models.CharField(blank=True, db_column='Attendance', max_length=50, null=True)),
                ('notes', models.TextField(max_length=15)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'db_table': 'CourtDates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_ID', models.TextField(max_length=15)),
                ('bill_amt', models.IntegerField()),
                ('comments', models.TextField(max_length=15)),
                ('submit_by', models.TextField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhaseParms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phase', models.TextField(max_length=1)),
                ('SiteNum', models.CharField(max_length=30)),
                ('Screens', models.CharField(max_length=1)),
                ('StepSessions', models.CharField(max_length=2)),
                ('MtgsPerWeek', models.CharField(max_length=1)),
                ('TxSessionHrs', models.IntegerField()),
                ('Other', models.IntegerField()),
                ('MinPhaseDays', models.IntegerField()),
                ('CaseReviewFreq', models.CharField(max_length=30)),
                ('BillingAmount', models.IntegerField()),
                ('BillingTotal', models.IntegerField()),
                ('EmploymentHrs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sanctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_ID', models.TextField(max_length=15)),
                ('sanc_desc', models.TextField(max_length=250)),
                ('jail_days', models.IntegerField()),
                ('comm_srvc_hrs', models.IntegerField()),
                ('comm_srvc_name', models.TextField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_ID', models.TextField(max_length=15)),
                ('result', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
