# Generated by Django 2.1.8 on 2020-01-27 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='phasehistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='phase',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Note'),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='courtdate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
    ]
