# Generated by Django 2.1.8 on 2020-02-20 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screens',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='sanctions',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='phasehistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AddField(
            model_name='courtdates',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
    ]
