# Generated by Django 2.1.8 on 2020-01-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phaseparms',
            name='Phase',
            field=models.CharField(max_length=1),
        ),
    ]
