# Generated by Django 2.1.8 on 2020-01-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20200120_1610'),
        ('court', '0002_auto_20200111_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourtDates',
            new_name='CourtDate',
        ),
        migrations.RenameModel(
            old_name='Sanctions',
            new_name='Sanction',
        ),
        migrations.RenameModel(
            old_name='Screens',
            new_name='Screen',
        ),
    ]
