# Generated by Django 2.1.8 on 2020-02-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_auto_20200219_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasehistory',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
