# Generated by Django 2.1.8 on 2020-02-19 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_auto_20200208_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='phase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
