# Generated by Django 2.1.8 on 2020-02-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_auto_20200208_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='min_days',
            new_name='min_phase_days',
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='employment_hours',
            new_name='weekly_employment_hours',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='review_freq',
        ),
        migrations.AddField(
            model_name='phase',
            name='tx_sessions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phase',
            name='review_frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='phase',
            name='site_num',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='phase',
            name='step_sessions',
            field=models.IntegerField(),
        ),
    ]
