# Generated by Django 2.1.8 on 2020-02-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0004_auto_20200218_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='notes',
        ),
        migrations.AlterField(
            model_name='phase',
            name='review_freq',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], max_length=30),
        ),
        migrations.AlterField(
            model_name='phase',
            name='site_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phase',
            name='step_sessions',
            field=models.IntegerField(default=1),
        ),
    ]
