# Generated by Django 2.1.8 on 2020-02-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0004_auto_20200220_2017'),
        ('court', '0004_auto_20200219_2219'),
    ]

    operations = [
    ]
