# Generated by Django 2.1.8 on 2020-02-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0005_auto_20200219_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='fees',
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
