# Generated by Django 2.1.8 on 2019-06-13 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_role', models.IntegerField(choices=[(0, 'Drug Court Team'), (1, 'DA'), (2, 'Defense'), (3, 'Pretrial'), (4, 'Screener'), (5, 'Developer')], null=True, verbose_name='User Role')),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
    ]
