# Generated by Django 2.1.8 on 2019-07-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.IntegerField(choices=[(0, 'Drug Court Team'), (1, 'DA'), (2, 'Defense'), (3, 'Pretrial'), (4, 'Screener'), (5, 'Developer')], default=0, null=True, verbose_name='User Role'),
        ),
    ]
