# Generated by Django 2.1.8 on 2019-07-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Drug Court Team', 'Drug Court Team'), ('DA', 'DA'), ('Defense', 'Defense'), ('Pretrial', 'Pretrial'), ('Screener', 'Screener'), ('Developer', 'Developer')], max_length=20, null=True, verbose_name='User Role'),
        ),
    ]
