# Generated by Django 2.1.8 on 2019-07-11 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('status', django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Screening'), (2, 'In Program')], max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_initial', models.CharField(max_length=1, null=True)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'clients',
                'managed': True,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter notes here.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_type', models.CharField(choices=[('Court', 'Court')], default='Court', max_length=25)),
                ('author', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'verbose_name_plural': 'notes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], max_length=20, verbose_name='Referral Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'permissions': [('can_approve', 'Can Approve Referral'), ('can_reject', 'Can Reject Referral')],
                'managed': True,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
    ]
