# Generated by Django 2.1.8 on 2019-07-16 03:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('status', django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Screening'), (2, 'In Program')], max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_initial', models.CharField(max_length=1, null=True)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'clients',
                'managed': True,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('verdict', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicSplitProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('question', models.CharField(max_length=50)),
                ('split_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter notes here.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_type', models.CharField(choices=[('Court', 'Court')], default='Court', max_length=25)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'verbose_name_plural': 'notes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_id', models.CharField(blank=True, choices=[(0, 'Not in System'), (1, 'Phase One'), (2, 'Phase Two'), (3, 'Phase Three')], max_length=20, null=True)),
                ('screens_per_week', models.IntegerField()),
                ('meetings_per_week', models.IntegerField()),
                ('fees', models.CharField(max_length=4)),
                ('review_frequency', models.IntegerField()),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('provider_type', models.CharField(choices=[(0, 'Drug Court')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=20, verbose_name='Referral Status')),
                ('referrer', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Provider')),
            ],
            options={
                'managed': True,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.AddField(
            model_name='provider',
            name='clients',
            field=models.ManyToManyField(through='intake.Referral', to='intake.Client'),
        ),
        migrations.AddField(
            model_name='decision',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Referral'),
        ),
        migrations.AddField(
            model_name='decision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='client',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Phase'),
        ),
    ]
