# Generated by Django 2.1.8 on 2019-07-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criminalbackground',
            options={'managed': True},
        ),
    ]
