# Generated by Django 2.1.8 on 2020-02-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
