# Generated by Django 2.1.8 on 2019-07-16 15:36

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorldProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('text', models.CharField(max_length=150)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.AlterField(
            model_name='phase',
            name='fees',
            field=models.CharField(blank=True, default='20', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='meetings_per_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phase',
            name='review_frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phase',
            name='screens_per_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=django_fsm.FSMField(default='Pending', max_length=20, verbose_name='Referral Status'),
        ),
    ]
