# Generated by Django 2.1.8 on 2019-07-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
