# Generated by Django 2.1.8 on 2020-02-16 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20200208_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='clients',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='client_num',
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_initial',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='referral',
            name='provider',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
