# Generated by Django 2.1.8 on 2020-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20200220_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
