# Generated by Django 2.1.8 on 2019-07-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20190716_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDate',
            fields=[
                ('court_date_id', models.AutoField(db_column='CourtDateID', primary_key=True, serialize=False)),
                ('court_date', models.DateTimeField(db_column='CourtDate')),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
                ('court_date_type', models.CharField(blank=True, db_column='CourtDateType', max_length=10, null=True)),
                ('attendance', models.CharField(blank=True, db_column='Attendance', max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Note')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Phase')),
            ],
            options={
                'db_table': 'Court',
                'managed': True,
            },
        ),
    ]
