# Generated by Django 2.1.8 on 2019-07-23 19:37

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20190723_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='date_received',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=django_fsm.FSMField(choices=[('Pending', 'Pending'), ('Screening', 'Screening'), ('In Program', 'In Program')], default='Pending', max_length=50),
        ),
    ]
