# Generated by Django 3.0.1 on 2020-01-11 16:22

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20200107_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtdate',
            name='phase',
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[('Pending', 'Pending'), ('Screening', 'Screening'), ('Accepted', 'Accepted')], default='Pending', max_length=50, null=True, verbose_name='Client Status'),
        ),
        migrations.AlterField(
            model_name='courtdate',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=django_fsm.FSMField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=40, verbose_name='Referral Status'),
        ),
    ]
