# Generated by Django 2.1.8 on 2019-07-11 21:16

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('intake', '0002_auto_20190711_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('verdict', django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=20, verbose_name='Verdict')),
            ],
            options={
                'permissions': [('can_decide', 'Can Approve')],
                'managed': True,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=20, verbose_name='Referral Status'),
        ),
        migrations.AddField(
            model_name='decision',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Referral'),
        ),
        migrations.AddField(
            model_name='decision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
