# Generated by Django 2.1.8 on 2019-07-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20190723_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
