# Generated by Django 2.1.8 on 2020-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20200216_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='provider',
            field=models.CharField(max_length=100),
        ),
    ]
