# Generated by Django 2.1.8 on 2019-07-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_courtdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdate',
            name='court_date',
            field=models.DateField(db_column='CourtDate'),
        ),
    ]
