# Generated by Django 2.1.8 on 2020-02-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20200216_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='provider',
        ),
    ]
