# Generated by Django 2.1.8 on 2019-07-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20190716_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdate',
            name='court_date_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Review', 'Review'), ('Final', 'Final')], db_column='CourtDateType', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courtdate',
            name='event',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Phase Appearance', 'Phase Appearance'), ('Graduation', 'Graduation'), ('Termination', 'Termination'), ('Special', 'Special')], max_length=50, null=True),
        ),
    ]
