# Generated by Django 2.1.8 on 2019-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20190723_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='made_by',
            field=models.CharField(choices=[('Drug Court Team', 'Drug Court Team'), ('DA', 'DA'), ('Defense', 'Defense'), ('Pretrial', 'Pretrial')], max_length=20, null=True),
        ),
    ]
