# Generated by Django 2.1.8 on 2019-07-17 19:25

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_auto_20190716_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=django_fsm.FSMField(choices=[('Pending', 'Pending'), ('Screening', 'Screening'), ('In Program', 'In Program')], max_length=50),
        ),
        migrations.AlterField(
            model_name='decision',
            name='verdict',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AlterField(
            model_name='note',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='intake.Client'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('Court', 'Court'), ('Treatment', 'Treatment'), ('General', 'General')], default='Court', max_length=25),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('Drug Court', 'Drug Court'), ('Other', 'Other')], max_length=20),
        ),
    ]
