# Generated by Django 2.1.8 on 2020-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_remove_referral_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
