# Generated by Django 2.1.8 on 2019-07-23 20:33

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_decision_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='verdict',
            field=django_fsm.FSMField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Verdict'),
        ),
    ]
