# Generated by Django 2.1.8 on 2019-07-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_auto_20190717_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrests', models.IntegerField(blank=True, db_column='Arrests', null=True)),
                ('felonies', models.IntegerField(blank=True, db_column='Felonies', null=True)),
                ('misdemeanors', models.IntegerField(blank=True, db_column='Misdemeanors', null=True)),
                ('firstarrestyear', models.IntegerField(blank=True, db_column='FirstArrestYear', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='ssn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='verdict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criminalbackground',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
        ),
    ]
