# Generated by Django 2.1.8 on 2019-07-24 19:15

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_auto_20190724_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=django_fsm.FSMField(choices=[('Pending', 'Pending'), ('Screening', 'Screening'), ('In Program', 'In Program')], default='Pending', max_length=50, verbose_name='Client Status'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='date_received',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=django_fsm.FSMField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Referral Status'),
        ),
    ]
