# Generated by Django 2.1.8 on 2019-08-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0009_auto_20190729_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='verdict',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Verdict'),
        ),
    ]
