# Generated by Django 2.2.4 on 2019-09-09 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0010_auto_20190805_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(blank=True, choices=[('Court', 'Court'), ('Treatment', 'Treatment'), ('General', 'General')], max_length=25, null=True),
        ),
    ]
