# Generated by Django 2.2.4 on 2019-09-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0011_auto_20190908_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdate',
            name='attendance',
            field=models.BooleanField(blank=True, db_column='Attendance', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='courtdate',
            table='CourtDate',
        ),
    ]
