# Generated by Django 2.1.8 on 2020-02-21 01:17

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('CellPhone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
                ('MessageSource', models.CharField(max_length=50)),
                ('IncomeSource', models.CharField(max_length=50)),
                ('YearlyIncome', models.IntegerField()),
                ('EducationYrs', models.CharField(max_length=50)),
                ('EducationLevel', models.CharField(max_length=50)),
                ('HighSchoolGrad', models.CharField(max_length=50)),
                ('GED', models.CharField(max_length=50)),
                ('MaritalStatus', models.CharField(max_length=50)),
                ('ChildNarrative', models.CharField(max_length=50)),
                ('EmployedAtStart', models.CharField(max_length=50)),
                ('EmployedAtGrad', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
