# Generated by Django 2.1.8 on 2020-02-21 03:43

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('NeedleUse', models.BooleanField()),
                ('FamilyofOriginYN', models.BooleanField()),
                ('FamilyofOriginUse', models.CharField(max_length=250)),
                ('TestType', models.CharField(max_length=50)),
                ('TestResults', models.CharField(max_length=250)),
                ('SubstanceUse', models.CharField(max_length=250)),
                ('Sobriety', models.CharField(max_length=50)),
                ('PrimaryDrug', models.CharField(max_length=250)),
                ('LastPositive', models.DateField()),
                ('Diagnosis', models.CharField(max_length=250)),
                ('Suicide', models.BooleanField()),
                ('Violence', models.BooleanField()),
                ('Health', models.CharField(max_length=250)),
                ('GhMedications', models.CharField(max_length=250)),
                ('Prenatal', models.CharField(max_length=250)),
                ('TBStatus', models.CharField(max_length=250)),
                ('PhysicalAbuse', models.BooleanField()),
                ('SexualAbuse', models.BooleanField()),
                ('InsuranceYN', models.BooleanField()),
                ('Insurance', models.CharField(max_length=250)),
                ('AddictionSeverityIndex', models.CharField(max_length=50)),
                ('LEP', models.BooleanField()),
                ('ASAM_LOC', models.CharField(max_length=250)),
                ('OutcomeComments', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Children',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='MilitaryService',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Pregnant',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='VAEligible',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
