# Generated by Django 2.1.8 on 2020-02-21 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20200220_2243'),
        ('core', '0002_auto_20200220_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intake.Client'),
            preserve_default=False,
        ),
    ]
