# Generated by Django 2.1.8 on 2020-03-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200220_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='Children',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='MilitaryService',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='Pregnant',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='VAEligible',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='client',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
