# Generated by Django 2.1.8 on 2019-07-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'managed': True},
        ),
    ]
