# Generated by Django 2.1.8 on 2019-05-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': False, 'verbose_name_plural': 'clients'},
        ),
    ]
