# Generated by Django 2.1.8 on 2019-06-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190611_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='dadecision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='DADecision', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='defensedecision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='DefenseDecision', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='pretrialdecision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='PretrialDecision', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='teamdecision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='TeamDecision', max_length=10, null=True),
        ),
    ]
