# Generated by Django 2.1.8 on 2019-06-14 18:19

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('cases', '0004_auto_20190613_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('status', django_fsm.FSMField(choices=[(0, None), (1, 'Pending Evaluation'), (2, 'Pending Evaluation')], max_length=50)),
                ('birth_date', models.DateField()),
                ('created_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('provider_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(max_length=20, verbose_name='Referral Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Provider')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='referrals',
            options={'managed': True, 'verbose_name_plural': 'referrals'},
        ),
        migrations.AddField(
            model_name='provider',
            name='clients',
            field=models.ManyToManyField(through='cases.Referral', to='cases.Client'),
        ),
    ]
