# Generated by Django 2.1.8 on 2019-06-14 20:02

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20190614_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'permissions': [('can_approve', 'Can Approve Referral'), ('can_reject', 'Can Reject Referral')]},
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Screening'), (2, 'In Program')], max_length=50),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=django_fsm.FSMField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], max_length=20, verbose_name='Referral Status'),
        ),
    ]
