# Generated by Django 2.1.8 on 2019-06-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('cases', '0006_auto_20190614_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter notes here.')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='client',
            name='middle_initial',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
