# Generated by Django 2.1.8 on 2020-01-06 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ObjDescrip', models.TextField(max_length=250)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProbGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ProbDescrip', models.TextField(max_length=250)),
                ('GoalDescrip', models.TextField(max_length=250)),
                ('ProbGoalStatus', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Referred', 'Referred'), ('Referred to Case Mgmt', 'Referred to Case Mgmt'), ('Deferred', 'Deferred'), ('Resolved', 'Resolved'), ('Refused', 'Refused')], max_length=1)),
                ('Obj_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.Objectives')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ItemDescription', models.TextField(max_length=250)),
                ('StaffRating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('ClientRating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('ObjID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.Objectives')),
                ('ProbGoalID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.ProbGoals')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TxAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('AbsenceReason', models.CharField(choices=[('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused'), ('Medical', 'Medical')], max_length=1)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TxProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('NoteType', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group'), ('Staffing', 'Staffing'), ('Contact', 'Contact')], max_length=1)),
                ('Problems', models.TextField(max_length=250)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
