# Generated by Django 2.1.8 on 2020-02-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probgoals',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
