# Generated by Django 2.1.8 on 2020-01-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20200120_1610'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TxAttendance',
            new_name='TxSession',
        ),
    ]
