# Generated by Django 2.1.8 on 2020-02-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_auto_20200208_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='client_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='met_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='tx_rating',
            field=models.IntegerField(blank=True),
        ),
    ]
