# Generated by Django 2.1.8 on 2020-02-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20200216_0135'),
        ('treatment', '0002_auto_20200208_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objectives',
            new_name='Objective',
        ),
        migrations.RenameModel(
            old_name='ProbGoals',
            new_name='ProbGoal',
        ),
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='TxAttendance',
            new_name='TxSession',
        ),
    ]
