# Generated by Django 2.1.8 on 2020-03-17 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_auto_20200220_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probgoals',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='treatment.Objectives'),
        ),
    ]
