# Generated by Django 2.1.8 on 2020-01-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20200124_1930'),
        ('treatment', '0002_auto_20200124_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objectives',
            new_name='Objective',
        ),
        migrations.RenameModel(
            old_name='ProbGoals',
            new_name='ProbGoal',
        ),
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
