# Generated by Django 2.1.8 on 2020-02-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20200218_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='met_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
