# Generated by Django 2.1.8 on 2020-02-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_auto_20200218_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='client_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='tx_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
